### ISSUE TITLE
The docker process doesn't work

### ISSUE THREAD

**Issue by lserveriiev** [sbeliakou/playpit-labs#10]
Hi there.

I'm trying to execute docker commands in the platform's console but I cannot do this. The docker process is down. When I run 
```
systemctl status docker
```
I get 
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-11-28 17:58:58 UTC; 10min ago
     Docs: https://docs.docker.com
  Process: 496 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.so>
 Main PID: 496 (code=exited, status=1/FAILURE)

Nov 28 17:58:58 docker-host systemd[1]: docker.service: Service RestartSec=2s expired, schedu>
Nov 28 17:58:58 docker-host systemd[1]: docker.service: Scheduled restart job, restart counte>
Nov 28 17:58:58 docker-host systemd[1]: Stopped Docker Application Container Engine.
Nov 28 17:58:58 docker-host systemd[1]: docker.service: Start request repeated too quickly.
Nov 28 17:58:58 docker-host systemd[1]: docker.service: Failed with result 'exit-code'.
Nov 28 17:58:58 docker-host systemd[1]: Failed to start Docker Application Container Engine.
Nov 28 17:59:14 docker-host systemd[1]: docker.service: Start request repeated too quickly.
Nov 28 17:59:14 docker-host systemd[1]: docker.service: Failed with result 'exit-code'.
Nov 28 17:59:14 docker-host systemd[1]: Failed to start Docker Application Container Engine.
```
My operating system is Windows 10.

**Comment by cepxuo** [comment]
I confirm having the same error on Windows 10

**Comment by jazZcarabazZ** [comment]
> Hi there.
> 
> I'm trying to execute docker commands in the platform's console but I cannot do this. The docker process is down. When I run
> 
> ```
> systemctl status docker
> ```
> 
> I get
> 
> ```
> ● docker.service - Docker Application Container Engine
>    Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Sat 2020-11-28 17:58:58 UTC; 10min ago
>      Docs: https://docs.docker.com
>   Process: 496 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.so>
>  Main PID: 496 (code=exited, status=1/FAILURE)
> 
> Nov 28 17:58:58 docker-host systemd[1]: docker.service: Service RestartSec=2s expired, schedu>
> Nov 28 17:58:58 docker-host systemd[1]: docker.service: Scheduled restart job, restart counte>
> Nov 28 17:58:58 docker-host systemd[1]: Stopped Docker Application Container Engine.
> Nov 28 17:58:58 docker-host systemd[1]: docker.service: Start request repeated too quickly.
> Nov 28 17:58:58 docker-host systemd[1]: docker.service: Failed with result 'exit-code'.
> Nov 28 17:58:58 docker-host systemd[1]: Failed to start Docker Application Container Engine.
> Nov 28 17:59:14 docker-host systemd[1]: docker.service: Start request repeated too quickly.
> Nov 28 17:59:14 docker-host systemd[1]: docker.service: Failed with result 'exit-code'.
> Nov 28 17:59:14 docker-host systemd[1]: Failed to start Docker Application Container Engine.
> ```
> 
> My operating system is Windows 10.

You can solve this problem by turning off the use of WSL 2

![2021-02-25_20-46-29](https://user-images.githubusercontent.com/49513297/109261617-21191080-7811-11eb-80c6-bda256f39549.png)

**Comment by lserveriiev** [comment]
The issue has been resolved, thanks a lot.
